### ISSUE TITLE
i wanna help

### ISSUE THREAD

**Issue by rares45** [slowscript/warpinator-android#1]
I know you are working alone right now. It's that intentional? Can I help? I could work on the design, user experience and fixing some bugs if you want. What's your opinion about Kotlin? And if I can help, what's the PR Workflow?

Edit: Do you really like that purple?
Edit 2: Can I translate it to Romanian?
Edit 3: How are you planning to implement the favourite function?

**Comment by slowscript** [comment]
Of course you can help. I'm not very good at design so if you could help with that I would appreciate it. However I'm currently working on some major changes and want to release a beta version by the end of next week, so it would be probably better if you wait for after that.

I don't know much about Kotlin, I plan to keep this project in Java. I also don't have any special PR workflow. Just open a PR (or a draft PR if you are working on something and want to let me/others know about it).

I chose that purple because it vaguely resembles the color on the icon of the original Warpinator. You can change that if you want.

I haven't gotten to making strings translatable yet. Most of them are still hardcoded.

The "favourite" function is on my todo list. I haven't thought about implementation details yet.

**Comment by rares45** [comment]
> I'm not very good at design so if you could help with that I would appreciate it.

Already done it.

> so it would be probably better if you wait for after that.

Too late. I was bored today so I spent my time working on this. I think I'm gonna make a PR draft and fix the conflicts(if any) after you push your commits. I think Git should do it for me.

> I don't know much about Kotlin, I plan to keep this project in Java.

I know both of them, that's why I asked. I have no problem with Java.



> I haven't gotten to making strings translatable yet. Most of them are still hardcoded.

Fixed that already.
