### ISSUE TITLE
Cannot find android device with linux mint 21.1

### ISSUE THREAD

**Issue by Baldovska** [slowscript/warpinator-android#117]
I'm trying to connect to warpinator android from linux mint 21.1.
I have tried both flatpak and system package. When I try nc -zvu 192.168.0.*** 5353 I get Connection to 192.168.0.*** 5353 port [udp/mdns] succeeded!. Both group codes are same. I'm sure I put the right network interface. No idea what could be wrong.
[latest.log](https://github.com/slowscript/warpinator-android/files/10386810/latest.log)

**Comment by DanSaintAndre** [comment]
I have two(2) Android devices.  One works; one doesn't.  My phone (Galaxy Note-20 Ultra) is Android 13 and does not work. My tablet (Galaxy Tab S6 S-Pen) is Android 12 and works. Both devices are Port=42000.
I have two(2) Linux Mint 21.1 workstations. One uses transfer port 42010 and registration port 42001. The other uses transfer port 42020 and registration port 42001. Both workstations have the same issues. Both LM workstations run v1.4.4 while the devices run v1.5.3.

QUESTION -- How do I configure so that my primary LM workstation sees both devices whenever all devices are on and connected to the same in-home or in-office LAN?

QUESTION -- How do I configure so that both workstations and both devices are all connected?

When I say "works," I mean that Linux Mint 21.1 sees the device and indicates a live connection.
When I say "not working," I mean that Linux Mint 21.1 either does not see the device or it sees the device but does not enable a live connection. Another issue with the phone is that it does not start automatically on device power on or restart.

Thank you in advance,
~~~ 0;-Dan
Covington, LA  USA

**Comment by slowscript** [comment]
@Baldovska I have now seen the log you have posted in the Linux repo and it seems that the two devices are on a different network. One has a 192.168.0.* address and the other has a 192.168.1.* address. Multicast packets (the device announcement) typically cannot reach a different network, even though unicast packets get routed correctly (the `nc` command). This can only be resolved by changing your router configuration (e.g. not separating WiFi and Ethernet networks) but as I don't know your specific network setup I cannot provide more specific advice.

@DanSaintAndre What I understood is that you have a Android 13 device that cannot be seen by other workstations.
The requirement for being seen is that the devices are on the same network and can send multicast UDP packets between their 5353 ports (the protocol is known as mDNS/zeroconf/Bonjour/...). This means the firewalls along the way allow the port and that the router correctly distributes multicast packets to all interested parties on the network. Routers typically don't forward these packets outside their network. If some packets got lost you can try invoking a manual reannounce from the menu or restart the application.

What also could be a problem is that if you have at some point synchronized app data from the tablet to the phone or the other way (via your Google account), the unique identifier of the Warpinator instance was synced as well and now both devices are presenting as one. The fix is to clear data on one of the devices (not reinstall, otherwise the cloud backup is restored).

The connection only requires the ports that appear in the settings to be allowed in the firewall of each device (both UDP and TCP). If the connection fails, it will automatically reconnect after a timeout or you can tap the reconnect button to do it immediately. If the phone gets stuck at waiting for duplex and the other device does not appear to be making a connection, you can try restarting the application on one of the offending devices. Since version 1.6 (Android) it should not matter which one. Previously it had to be both.

**Comment by Baldovska** [comment]
> @Baldovska I have now seen the log you have posted in the Linux repo and it seems that the two devices are on a different network. One has a 192.168.0.* address and the other has a 192.168.1.* address. Multicast packets (the device announcement) typically cannot reach a different network, even though unicast packets get routed correctly (the `nc` command). This can only be resolved by changing your router configuration (e.g. not separating WiFi and Ethernet networks) but as I don't know your specific network setup I cannot provide more specific advice.
> 
> @DanSaintAndre What I understood is that you have a Android 13 device that cannot be seen by other workstations. The requirement for being seen is that the devices are on the same network and can send multicast UDP packets between their 5353 ports (the protocol is known as mDNS/zeroconf/Bonjour/...). This means the firewalls along the way allow the port and that the router correctly distributes multicast packets to all interested parties on the network. Routers typically don't forward these packets outside their network. If some packets got lost you can try invoking a manual reannounce from the menu or restart the application.
> 
> What also could be a problem is that if you have at some point synchronized app data from the tablet to the phone or the other way (via your Google account), the unique identifier of the Warpinator instance was synced as well and now both devices are presenting as one. The fix is to clear data on one of the devices (not reinstall, otherwise the cloud backup is restored).
> 
> The connection only requires the ports that appear in the settings to be allowed in the firewall of each device (both UDP and TCP). If the connection fails, it will automatically reconnect after a timeout or you can tap the reconnect button to do it immediately. If the phone gets stuck at waiting for duplex and the other device does not appear to be making a connection, you can try restarting the application on one of the offending devices. Since version 1.6 (Android) it should not matter which one. Previously it had to be both.

Exactly as you commented. I had wrong ip adress on my phone. Changed dhcp settings on my wifi router.
