### ISSUE TITLE
HTTP File Server Pro - make images bigger

### ISSUE THREAD

**Issue by chaoscreater** [slowscript/warpinator-android#131]
Hi there,

Firstly, I apologize for posting in the wrong place. I couldn't find a way to contact you via email and I don't see a project for HTTP File Server Pro under your Github, so I'm posting it here instead.

I'm using your HTTP File Server Pro app and it's great. I just have one small feature request - could you please make the photos/pictures display at a much bigger size please? Or perhaps allow the users to define the size (whether it's done in the settings, or on the actual webpage as a zoom button of some sort). I can zoom in the page on my browser to make the photos look bigger, but everything else (the text, other buttons on the page, etc) will look bigger as well. I'm already using Compact display and it's not as big as I'd like.

Ideally, I'd like to display using List and have the images display as a large icon, so I can see what the photos are without having to use something like Imagus to zoom hover on the photo to see them bigger, or having to zoom in on the webpage. It would be great if you could add this functionality!

**Comment by chaoscreater** [comment]
Came up with my own solution!

I created a userscript (with the help of ChatGPT) to modify the elements on the page. To use this, just download something like ViolentMonkey or Tampermonkey and load this userscript:

https://pastebin.com/eZYxmhj6

Note that the match is set to `https://*:8080/files/DCIM/*`. If you're using a different port for your HTTP File Server, then change it to use that port. The script basically kicks in whenever you browse to the DCIM folder on your HTTP File Server.

The script sets the default zoom level on the images to 100%, which is much bigger than the default zoom level. It also gives you an option to adjust the zoom level using the slider at the bottom left, or you can set the zoom % in the text box. These settings will be saved even if the page is refreshed.

The preview tickbox can be used to toggle between the preview lower quality images, or the original image. By default, HTTP File Server display preview quality image, which I don't like. I think the main reason for this is for speed & performance. If you have thousands of images, then loading the original quality will make the page slow. You can toggle between preview and no-preview and the images will update accordingly.

P.S - I'm not a developer at all, I barely know Javascript. ChatGPT did most of the heavy lifting, so please don't expect me to update the code or whatever, I'm just sharing this as I found it useful and thought it might help someone.

![image](https://github.com/slowscript/warpinator-android/assets/18227319/b9792243-d877-4d66-8f07-1b42a5d90fc3)

**Comment by slowscript** [comment]
Hi,

In case you have any further questions or suggestions, there is an email listed on the about page of HTTP File Server (near the bottom) as well as on the Google Play page.

Having bigger preview images is on my to-do list, as well as implementing a gallery view that allows browsing the images on full screen in chronological order. Thank you for the suggestion on how the previews might behave. Your script looks nice, especially considering it was made using ChatGPT. I will probably add a setting for preview quality into the app settings instead of web UI though, so you can have bigger and less pixelated previews while still saving bandwidth.

I'm closing this issue because it is unrelated to the project, but I will still post an update here when your request gets implemented.

**Comment by slowscript** [comment]
Hi, version 1.6 includes a new Previews display mode (128px size, I might add a setting for that later) and a gallery view when you open one of the images. Hopefully you will find it useful.
