### ISSUE TITLE
Can't connect to Warpinator on desktop

### ISSUE THREAD

**Issue by rares45** [slowscript/warpinator-android#2]
The app sees the instance on my PC (running Linux Mint),  but it can't get the name of it and fails to connect.

![Screenshot_20201129-184357](https://user-images.githubusercontent.com/42469755/100548078-0e735780-3273-11eb-9d67-ca7f7ba1437d.png)

But the desktop sees everything right.

Is this planned or should I start fixing it?

**Comment by slowscript** [comment]
I think I know what this is. It is an issue with the Linux version of Warpinator. It generates a certificate that is missing some information which is why the Android version refuses to connect to it.
I've had it fixed in my local build for a while now but haven't submitted a PR yet. I'll do it probably tomorrow.

**Comment by slowscript** [comment]
The issue upstream should be fixed now (version 1.0.9). Please check if it has resolved your problem too

**Comment by rares45** [comment]
I don't see any commit newer

**Comment by slowscript** [comment]
I meant in the Linux version of Warpinator. This has been merged yesterday: https://github.com/linuxmint/warpinator/pull/70

**Comment by rares45** [comment]
Aaahhh. Ok. Let me check

**Comment by rares45** [comment]
It works. Sorry for waiting so much, but the package wasn't built for Linux Mint so I had to build it myself.

What do you think about my PR?
