### ISSUE TITLE
Failed to create certificate

### ISSUE THREAD

**Issue by Adyb123** [slowscript/warpinator-android#33]
Just downloaded to Android phone and it comes up with FAILED TO CREATE CERTIFICATE.  
![Screenshot_20210503-070721_Warpinator](https://user-images.githubusercontent.com/83570764/116846089-74c42380-abdf-11eb-909f-2f5b0452f49e.jpg)

Galaxy note 10+ 5g. Latest android update.

Can you advise please. Thanks Ade

**Comment by Adyb123** [comment]
Sorry should have mentioned. Tried with mobile data on and off. Checked WiFi its definitely on and connected.

**Comment by slowscript** [comment]
Could you please try renaming your phone to something simple and short (no spaces or special characters)? It should be in "About phone" section or Bluetooth settings. The name of your phone is used as name of issuer on the certificate and there are probably some restrictions on what it can contain. Since you have a Note 10+ and assuming you haven't renamed it, the "+" could be the problem. If it turns out to be the case, I will make sure it skips these characters.

**Comment by Adyb123** [comment]
Hi

It worked, thanks for the help.

I look forward to using it.

Thanks again

Ade

**Comment by toxision** [comment]
Ok that's a good hint. However, even giving it a much simpler name, it still fails with the same message like above. I've tried "psmart" but no chance passing that error.

**Comment by slowscript** [comment]
That's interesting. Have you actually changed your phones name and not just in the app? Maybe try wiping Warp's data before running it too. If that doesn't help, would you be able to obtain a log with adb?

**Comment by toxision** [comment]
Thank you for considering to help again.
I've uninstalled and reinstalled the app again. To make sure I changed the phone name once more, restarted and then installed the Warpinator client -> error remains. I think with "psmart" I gave it not so complicated name. Interestingly my much older tablet, still running Android 7, has no issues whatsoever. The newer phone (Huawei) is running on Android 10.
Unfortunately I couldn't manage to start the app with adb. My knowledge with that is still very limited. But I will look it up and give it another try and check for output logs.
