### ISSUE TITLE
Allow to see what is the default download path

### ISSUE THREAD

**Issue by pleiozc** [slowscript/warpinator-android#41]
In case user wants to confirm it via GUI.

![f2_1_1](https://user-images.githubusercontent.com/79718929/117301302-e35be800-ae50-11eb-922f-55f89e6a25b3.png)
![w1_1](https://user-images.githubusercontent.com/79718929/117301320-e9ea5f80-ae50-11eb-9347-065e5cd399d1.png)

**Comment by rares45** [comment]
Good idea. I'll add that right away

**Comment by slowscript** [comment]
There is no default download path (for now). Also, if you want to see the current download path, it will not look like "/storage/emulated/0/..." but more like "content://com.android.externalstorage.documents/..." since we are using the Storage Access Framework (SAF). Normal way of dealing with files has been deprecated in Android 11 and I don't want to maintain two implementations. This is also why you have to select a download path when launching the application for the first time: it's no longer possible to manipulate with files without user's explicit permission.

**Comment by pleiozc** [comment]
Is there any way to hide preceding part from full path:

'/tree/primary' 

and only show what's following the colon ':' for example: 

'Documents/Warpinator'

to make easier to read?

![Warpinator](https://user-images.githubusercontent.com/79718929/118711296-cb437b80-b7f5-11eb-9de9-636744de0ec0.png)

**Comment by rares45** [comment]
I actually like it. Especially if you have the folder set to home. It's not just blank.

**Comment by slowscript** [comment]
The "primary" part is important. It means that you are in your primary storage volume. If you were in your SD card, USB drive etc. it would be different
