### ISSUE TITLE
Odd behaviour linux - wifi or bluetooth?

### ISSUE THREAD

**Issue by Andy2051** [slowscript/warpinator-android#54]
See this topic on the linux mint forum:
[https://forums.linuxmint.com/viewtopic.php?p=2024757#p2024757](url)
With my T430 thinkpads will not work unless bluetooth is enabled. Other user - no problems phone <-> pc with bluetooth disabled?

Laptops are running LM20.1 and the phone is a Sony Xperia XZ1 compact.

Do like it and thank you for taking the time to develop it.

**Comment by slowscript** [comment]
This is strange. Bluetooth definitely is not used for transfer. The only way any Bluetooth API is used is to get the name of the phone - which should work even with BT disabled - and I'm pretty sure I've already made it default to "Android phone" when anything fails. I think the issue is somewhere else.

Sometimes the connection initial connection fails because it starts before the other side is ready to accept it. The Linux version retries every 30 seconds, the Android version will either pick it up automatically or you can force it to reconnect with the button next to the status icon. It is also good to know if it failed to connect at all or if it just failed to get duplex (icon with arrow and 3 dots appears before changing to the failed icon).

If nothing helps, could you please try getting a debug log (as described [here](https://github.com/slowscript/warpinator-android/blob/master/connection-issues.md)), ideally while running this debug build [warpinator-debug.zip](https://github.com/slowscript/warpinator-android/files/6603100/warpinator-debug.zip) (it produces more verbose messages). Debug logs are crucial for me to understand what the application is trying to do and why it is not working.

**Comment by Andy2051** [comment]
Thanks for the response, subsequently it worked with bluetooth disabled on both phone and PC (LM201.1), which has left me more confused. If I can make it repeatable I'll try and get a debug log for more info. In the meantime suggest you close this issue.

**Comment by Andy2051** [comment]
Closed
