### ISSUE TITLE
[Feature request] Add refresh button (that restarts the service)

### ISSUE THREAD

**Issue by AndreiMiculita** [slowscript/warpinator-android#93]
The connection seems to break a lot, and stopping then starting the service seems to fix things most of the time.

Adding a refresh button (🔄) would help make this easier, while also having the psychological benefit of making the user feel like they're doing something to help. Kinda like pedestrian crossing buttons.

**Comment by slowscript** [comment]
The already present "refresh" button doesn't work? It reattempts the connection (this also should happen on its own regularly). If you need to restart the service there is something wrong that should be fixed. Having a button for this is more of a hack than a feature, although I'm not ruling it out if it turns out to be necessary.

Can you describe in more detail what exactly "breaks"? Do you ever establish a connection in the first place? Is there some situation that breaks your connection? The most probable one I think could be changing the network (switching between WiFi access points or hotspot). Also, can you test whether this only happens with remotes running certain operating system (and corresponding version of Warpinator)?

**Comment by AndreiMiculita** [comment]
Hey! 

It just happened again now. I've had the Warpinator service running for many days (possibly weeks) on my phone. And just opened Warpinator on my PC, and neither of the programs sees each other. Both the PC Warpinator and the Android Warpinator are saying "No other devices found".

I've tried "Reannounce" and "Rescan for devices" and neither changed anything. Then I stopped the service and started the mobile app again and now it works.

Sorry for the late reply but I don't use Warpinator very often, and it happens like in 1/4 cases. so the issue itself doesn't pop up a lot for me.

I am using the mobile app v1.4.4 on Android 10, One UI 2.5, kernel version 4.9.118-22256815 on a Samsung Galaxy S9
And the Mint program v1.2.9 on Linux Mint 20.3 on Lenovo Legion S7 15IMH5

**Comment by slowscript** [comment]
Hi,

running the service for that long isn't really supported right now. I never intended it to be run for more than some tens of minutes, just enough to transfer the files and then quit. One reason being that making Android apps reliably run in background is quite a headache. Each vendor has some different battery optimizing magic that causes all kinds of funky behaviour. If you let it run for a long enough time, Android will just kill/pause something because of battery or memory constraints. Or if you disable all battery saving I'm sure it will drain it very quickly.

I even considered adding a timeout to automatically stop the service after an hour of inactivity. The only reason I didn't is that someone made a PR with an "autostart after boot" feature and stopping the service would defeat this (to me not so clear) use case.

As for the restart button, I don't think there is a big difference between restarting the app properly (Quit or Stop service buttons) and having a button that does the same. Also having such a button assumes that the user knows what he's doing and won't push it repeatedly, likely leaving the app in an even more broken state than before. I think most users know that the basic solution to most unusual problems is restarting the application.

**Comment by AndreiMiculita** [comment]
Ah yes, never noticed that the "Stop service" button actually stops the app completely. Shame that it can't be reliably run in the background. Very likely that's the issue, as I've had trouble with Samsung's battery saving before.

I'd think the "autostart after boot" feature was probably made under the assumption that the service can be kept reliably in the background. But yeah, a timeout after an hour sounds good.

**Comment by StickyDigit** [comment]
If introducing auto off, Is it possible to add an alternative "grab wakelock" option like termux has, for always-on and/or mains connected devices, to allow reliable service from boot to shutdown?


On 12 March 2022 19:39:53 GMT, Pavel H ***@***.***> wrote:
>Hi,
>
>running the service for that long isn't really supported right now. I never intended it to be run for more than some tens of minutes, just enough to transfer the files and then quit. One reason being that making Android apps reliably run in background is quite a headache. Each vendor has some different battery optimizing magic that causes all kinds of funky behaviour. If you let it run for a long enough time, Android will just kill/pause something because of battery or memory constraints. Or if you disable all battery saving I'm sure it will drain it very quickly.
>
>I even considered adding a timeout to automatically stop the service after an hour of inactivity. The only reason I didn't is that someone made a PR with an "autostart after boot" feature and stopping the service would defeat this (to me not so clear) use case.
>
>As for the restart button, I don't think there is a big difference between restarting the app properly (Quit or Stop service buttons) and having a button that does the same. Also having such a button assumes that the user knows what he's doing and won't push it repeatedly, likely leaving the app in an even more broken state than before. I think most users know that the basic solution to most unusual problems is restarting the application.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/slowscript/warpinator-android/issues/93#issuecomment-1065950486
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from a phone. Please excuse my brevity.

**Comment by AndreiMiculita** [comment]
P.S. It is strange though that the issue I mentioned persists even when the app itself is open and focused on the Android device.

**Comment by slowscript** [comment]
> Is it possible to add an alternative "grab wakelock" option like termux has, for always-on and/or mains connected devices

Ah, now I see why one would want the autostart feature. My answer to the question is: maybe? It's not my use case and I currently don't have a device that I could leave at home for long enough to test this. I'm also not sure a full wakelock is necessary just to listen on packets. All we need is for Android to not kill it. Would have to do a lot of investigation before implementing this. If someone wants to give it a shot then I'll accept the PR.

> It is strange though that the issue I mentioned persists even when the app itself is open and focused on the Android device.

What do you mean? You start the app fresh (after properly quitting) and it doesn't connect to your PC? There is no recovery mechanism that would make it fix itself. It probably doesn't even know that it's broken (unless there is some error in the log).

**Comment by AndreiMiculita** [comment]
> What do you mean? You start the app fresh (after properly quitting) and it doesn't connect to your PC? There is no recovery mechanism that would make it fix itself. It probably doesn't even know that it's broken (unless there is some error in the log).

I just swipe the app away from the recent app list. Does "properly quitting" also mean pressing "Stop service" in the notification? Because I only do the former (and in this case, yes, the app does not connect - or even see - the PC, and vice versa).

**Comment by slowscript** [comment]
Yes, swiping it away just ends the UI part, the service keeps running in the background as long as the persistent notification is present. This is just in case you are sending something large and want to do something else on your phone. Properly quitting means either using the Quit option in menu or Stop service in the notification.

**Comment by AndreiMiculita** [comment]
> This is just in case you are sending something large and want to do something else on your phone..

Then it sounds to me like it would be easy to check for this though? Just close the service and the notification once the large transfer is done?

**Comment by slowscript** [comment]
Yes, I have implemented something like this a week or so ago. I just want to make sure it is reliable and doesn't cause issues. It stops the service when the app is cleared from recents or after a minute of the app being in background with no transfer running. The minute long timeout is so that if the users reopens the app it doesn't have to search for devices again. I hope this behavior will be more intuitive.
